name: dumulmury
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
    sdk: '>=2.7.0 <3.0.0'

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^0.1.3
    equatable: ^1.2.0
    flutter_bloc: ^4.0.0
    http: ^0.12.1
    pedantic: ^1.9.0
    flexiblelayout: ^1.0.1+1
    url_launcher: ^5.4.10

dev_dependencies:
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true

    assets:
        - assets/images/github_logo.png
        - assets/images/github_logo_w.png
        - assets/images/github_mark.png
        - assets/images/github_mark_w.png
        - assets/images/octocat.png

    fonts:
        - family: NanumSquare
          fonts:
              - asset: assets/fonts/NanumSquare_acR.ttf
              - asset: assets/fonts/NanumSquare_acL.ttf
              - asset: assets/fonts/NanumSquare_acEB.ttf
                weight: 900
              - asset: assets/fonts/NanumSquare_acB.ttf
                weight: 600
